sudo: required

language: bash

services:
 - docker

env:
  - TAG=4.2.0
  - TAG=4.2.1
  - TAG=4.2.2
  - TAG=4.2.3
  - TAG=4.2.4
  - TAG=4.2.4.1
  - TAG=5.0.0
  - TAG=5.0.1
  - TAG=5.0.2
  - TAG=latest

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./travis-build.sh
